name: Hakim's Tri-Daily Commit

on:
  schedule:
    - cron: '0 0 * * *'  # This runs every day at midnight UTC
    # To run every 3 days at midnight UTC:
    # - cron: '0 0 */3 * *'

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: main

    - name: Create file and commit
      run: |
        FILE="commit_number.md"
        if [ ! -f "$FILE" ]; then
          echo "Hello, my name is Abdul Hakim Norazman" > "$FILE"
          echo "commit number: 1" >> "$FILE"
        else
          CURRENT_COUNT=$(grep -oP 'commit number: \K\d+' "$FILE")
          if [ -z "$CURRENT_COUNT" ]; then
            CURRENT_COUNT=0
          fi
          NEXT_COUNT=$((CURRENT_COUNT + 1))
          sed -i "/commit number: /c\commit number: $NEXT_COUNT" "$FILE"
        fi
        git config --global user.name "Abdul Hakim Norazman"
        git config --global user.email "ahnorazman@gmail.com"
        git add "$FILE"
        git commit -m "Hello, my name is Abdul Hakim Norazman nice to meet you"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/FLABDUL/workflow.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
